SYMBOLS = ["BTC/USDT", "ETH/USDT", "SOL/USDT", "LINK/USDT", "ONDO/USDT"]
TIMEFRAME = "1m"
BASE_THRESHOLD = 0.01
BASE_RISK = 0.1
LEVERAGE = 20
MIN_VOLUME = 0
MIN_VOLATILITY = 0
DD_LIMIT = 0.30
STATE_FILE = "engine_state.json"

# ===== TIMING PARAMETERS =====
CHECK_INTERVAL = 5  # saniye
SIGNAL_DELAY = 2    # saniye
ENTRY_TIMEOUT = 10  # saniye
EXIT_TIMEOUT = 5    # saniye
WATCHDOG_INTERVAL = 30  # saniye

# ================= MOCK MODE =================
MOCK_MODE = True
MOCK_INITIAL_BALANCE = 10000

# ================= API & TELEGRAM =================
API_KEY = "DHurw9l4nILPLcEs0aw1exgRe5B0BBVY2RDLfJqF3eZmDF99aBnUSeHhyYsnXs34"
SECRET_KEY = "Z6b7MjOTvLo1hSbv3UdA4b4xhoFD1Qw0FAGlPuu7mB9Xb4P0Vl0Ndts39Hl7h1TC"
TELEGRAM_TOKEN = "8763094320:AAGSq3tXa6JWLsdYc40wqi9Xr4oMloPGuMU"
TELEGRAM_CHAT_ID = "6350700231"